# Make sure to check the documentation at http://goreleaser.com

project_name: dev-env

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download

builds:
  - env:
    - CGO_ENABLED=0
    - GO111MODULE=on
  - binary: '{{ .ProjectName }}'
    goos:
      - darwin
      - linux
      - windows
    goarch:
        - amd64
        -
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"


changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
