name: New issue for Reproducible Bug
about: "If you're sure it's reproducible and not just your machine: submit an issue so we can investigate."
labels: bug
issue_body: false
inputs:
  - type: description
    attributes:
      value: Please note we will close your issue without comment if you do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.
  - type: textarea
    attributes:
      label: "`devctl config view` output"
      required: true
  - type: textarea
    attributes:
      label: "`devctl version` output"
      required: true
  - type: textarea
    attributes:
      label: What were you trying to do (and why)?
      required: true
  - type: textarea
    attributes:
      label: What happened (include all command output)?
      required: true
  - type: textarea
    attributes:
      label: What did you expect to happen?
      required: true
  - type: textarea
    attributes:
      label: Step-by-step reproduction instructions (by running `brew` commands)
      required: true
