name: auto-changelog

on:
  pull_request:

jobs:
  auto-changelog:
    name: auto-changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: saadmk11/changelog-ci@v0.7.0
        with:
          changelog_filename: CHANGELOG.md
          config_file: .github/change-log-ci-config.json
          committer_username: github-action[bot]
          committer_email: github-action@github.com
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
