name: auto-merge

on:
  pull_request:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2.2.0
        with:
          target: minor
          github-token: ${{ secrets.GITHUB_TOKEN }}
